import * as fs from "fs";
import * as path from "path";

interface CharacterConfig {
  id: string;
  name: string;
  icon: string;
  description: string;
  images: string[];
  identityPrompt: string;
}

interface CharactersConfig {
  characters: CharacterConfig[];
}

function getMimeType(imagePath: string): string {
  const ext = imagePath.toLowerCase().split(".").pop();
  if (ext === "png") return "image/png";
  if (ext === "jpg" || ext === "jpeg") return "image/jpeg";
  if (ext === "webp") return "image/webp";
  return "image/png";
}

function main() {
  const projectRoot = path.resolve(__dirname, "..");
  const charactersJsonPath = path.join(
    projectRoot,
    "public",
    "characters",
    "characters.json"
  );
  const outputPath = path.join(
    projectRoot,
    "lib",
    "character-images.generated.ts"
  );

  // Read characters.json
  const charactersConfig: CharactersConfig = JSON.parse(
    fs.readFileSync(charactersJsonPath, "utf-8")
  );

  // Build image data map
  const imageDataMap: Record<string, string[]> = {};

  for (const character of charactersConfig.characters) {
    const imageDataUrls: string[] = [];

    for (const imagePath of character.images) {
      const fullPath = path.join(projectRoot, "public", imagePath);

      if (!fs.existsSync(fullPath)) {
        console.warn(`Warning: Image not found: ${fullPath}`);
        continue;
      }

      const imageBuffer = fs.readFileSync(fullPath);
      const base64 = imageBuffer.toString("base64");
      const mimeType = getMimeType(imagePath);
      const dataUrl = `data:${mimeType};base64,${base64}`;

      imageDataUrls.push(dataUrl);
    }

    imageDataMap[character.id] = imageDataUrls;
  }

  // Generate TypeScript file
  const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-character-images.ts

export const characterImages: Record<string, string[]> = ${JSON.stringify(imageDataMap, null, 2)};
`;

  fs.writeFileSync(outputPath, output, "utf-8");
  console.log(
    `Generated ${outputPath} with ${Object.keys(imageDataMap).length} characters`
  );
}

main();
